spring:
#  profiles:
#    active: bist
#    include: area,user
  application:
    name: ecomb-park-pool
  sleuth:
    sampler:
      probability: 1.0   #2.0后percentage改为probability
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ecomb
    username: root
    password: root
    hikari:
      #minimum-idle: 5
      #注意调节这个：连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      maximum-pool-size: 15
      auto-commit: true
      #一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      idle-timeout: 30000
      pool-name: JoyHikariCP
      #注意调节这个：一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒
      max-lifetime: 1730000
      #等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: 127.0.0.1
    port: 6380
    password:
    database: 10
    #    如果配置集群
    #    cluster:
    #      nodes:
    #        - 192.18.1.2:6380
    #        - 192.18.1.3:6381
    #        - 192.18.1.4:6382
    #      max-redirects: 3 # 获取失败 最大重定向次数
    lettuce:
      pool:
        max-active: 1 # 最大连接数， 默认为 8
        max-idle: 100  # 最大空闲， 默认为8
        min-idle: 20  # 最少空闲
        max-wait: 10000
    timeout: 5000
    #   哨兵模式配置
    #    sentinel:
    #      master: redis-master
    #      nodes: 127.0.0.1:26379,127.0.0.1:26380,127.0.0.1:26381
server:
  port: 8070
  tomcat:
    accept-count: 100
    #最大线程数
    max-threads: 600
    #最大连接数
    max-connections: 1600
    #编码方式
    uri-encoding: UTF-8
    #post提交数据最大大小，设置为0不限制
    max-http-post-size: 0
