spring:
  profiles:
    active: bist
#    include: area,user
  application:
    name: ecomb-web-app
  sleuth:
    sampler:
      probability: 1.0   #2.0后percentage改为probability
server:
  tomcat:
    #最大连接数
    max-connections: 500
    #最大线程数
    max-threads: 400
    #编码方式
    uri-encoding: UTF-8
    #post提交数据最大大小，设置为0不限制
    max-http-post-size: 0
