# redis 哨兵模式容器编排配置
version: '3.1'
services:
  # redis 配置
  master:
    image: redis
    container_name: redis-master
    ports:
      - 6380:6379
    networks:
      redis:
        ipv4_address: 192.18.1.2

  slave1:
    image: redis
    container_name: redis-slave-1
    ports:
      - 6381:6379
    command: redis-server --slaveof redis-master 6379
    networks:
      redis:
        ipv4_address: 192.18.1.3

  slave2:
    image: redis
    container_name: redis-slave-2
    ports:
      - 6382:6379
    command: redis-server --slaveof redis-master 6379
    networks:
      redis:
        ipv4_address: 192.18.1.4

  # sentinel配置
  sentinel-1:
    image: redis
    container_name: redis-sentinel-1
    restart: always
    volumes:
      - ./sentinel1.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    ports:
      - 26379:26379
    depends_on:
      - master
    networks:
      redis:
        ipv4_address: 192.18.1.10


  sentinel-2:
    image: redis
    container_name: redis-sentinel-2
    restart: always
    volumes:
      - ./sentinel2.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    ports:
      - 26380:26379
    depends_on:
      - master
    networks:
      redis:
        ipv4_address: 192.18.1.11

  sentinel-3:
    image: redis
    container_name: redis-sentinel-3
    restart: always
    volumes:
      - ./sentinel3.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    ports:
      - 26381:26379
    depends_on:
      - master
    networks:
      redis:
        ipv4_address: 192.18.1.12 

# 网络配置
networks:
  redis:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.18.1.0/24